name = "launcher"
description = "Keyboard-driven application launcher built on guikit"
version = "0.1.0-dev"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
tags = ["launcher", "gui"]

executables = ["launcher"]

[[depends-on]]
guikit = "*"

[[pins]]
guikit = { path = "../guikit" }

[[depends-on]]
textrender = "*"

[[pins]]
textrender = { path = "../textrender" }

[[depends-on]]
df_vulkan = "~0.1.0"

[[depends-on]]
openglada_glfw = "~0.9.0"

[[depends-on]]
utilada = "^2.9.0"
